name: Update index.html with current time

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run Python script # 파이썬 코드 실행
          run: python update_time.py
        - name: Commit updated index.html # 변경된 index.html 파일 커밋
          uses: EndBug/add-and-commit@v7
          with:
            author_name: LeeJeongMin0512
            author_email: doosan1201@gmail.com
            message: Update index.html with current time # 커밋 메시지
            add: "index.html" # 변경된 파일 추가



